[package]
name = "hamming-rust"
version = "0.1.0"
authors = ["yp.pan <pan.yiping.fi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3"
